CREATE SCHEMA "cscgs";

CREATE TABLE "cscgs"."game" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "status" int,
  "facilitator_user_id" int,
  "description" varchar,
  "create_time" timestamp,
  "start_time" timestamp,
  "end_time" timestamp
);

CREATE TABLE "cscgs"."round" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int,
  "name" varchar,
  "status" int,
  "description" varchar,
  "create_time" timestamp,
  "start_time" timestamp,
  "end_time" timestamp
);

CREATE TABLE "cscgs"."period" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rount_id" int,
  "name" varchar,
  "status" int,
  "description" varchar,
  "create_time" timestamp,
  "start_time" timestamp,
  "end_time" timestamp
);

CREATE TABLE "cscgs"."user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar,
  "description" varchar,
  "create_time" timestamp
);

CREATE TABLE "cscgs"."team" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int,
  "name" varchar,
  "description" varchar,
  "order" int,
  "create_time" timestamp
);

CREATE TABLE "cscgs"."game_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "team_id" int,
  "role" int,
  "partner" boolean,
  "description" varchar,
  "create_time" timestamp
);

CREATE TABLE "cscgs"."order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_user_id" int,
  "period_id" int,
  "num" int,
  "description" varchar,
  "create_time" timestamp
);

CREATE TABLE "cscgs"."delivery" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_user_id" int,
  "period_id" int,
  "num" int,
  "description" varchar,
  "create_time" timestamp
);

CREATE TABLE "cscgs"."inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_user_id" int,
  "period_id" int,
  "num" int,
  "description" varchar,
  "create_time" timestamp
);

ALTER TABLE "cscgs"."game" ADD FOREIGN KEY ("facilitator_user_id") REFERENCES "cscgs"."game_user" ("id");

ALTER TABLE "cscgs"."round" ADD FOREIGN KEY ("game_id") REFERENCES "cscgs"."game" ("id");

ALTER TABLE "cscgs"."period" ADD FOREIGN KEY ("rount_id") REFERENCES "cscgs"."round" ("id");

ALTER TABLE "cscgs"."team" ADD FOREIGN KEY ("game_id") REFERENCES "cscgs"."game" ("id");

ALTER TABLE "cscgs"."game_user" ADD FOREIGN KEY ("user_id") REFERENCES "cscgs"."user" ("id");

ALTER TABLE "cscgs"."game_user" ADD FOREIGN KEY ("team_id") REFERENCES "cscgs"."team" ("id");

ALTER TABLE "cscgs"."order" ADD FOREIGN KEY ("game_user_id") REFERENCES "cscgs"."team" ("id");

ALTER TABLE "cscgs"."order" ADD FOREIGN KEY ("period_id") REFERENCES "cscgs"."period" ("id");

ALTER TABLE "cscgs"."delivery" ADD FOREIGN KEY ("game_user_id") REFERENCES "cscgs"."game_user" ("id");

ALTER TABLE "cscgs"."delivery" ADD FOREIGN KEY ("period_id") REFERENCES "cscgs"."period" ("id");

ALTER TABLE "cscgs"."inventory" ADD FOREIGN KEY ("game_user_id") REFERENCES "cscgs"."game_user" ("id");

ALTER TABLE "cscgs"."inventory" ADD FOREIGN KEY ("period_id") REFERENCES "cscgs"."period" ("id");
